<?php

namespace App\Http\Controllers;

class AcademicController extends Controller
{
    public function inicio()
    {
        $cardAcademic = [
            ['nombre' => 'Ingeniero en Tecnologías de la Información', 'texto' => 'Universidad Politecnica del Valle de Toluca', 'imagen' => '1.svg', 'button' => 'Ir a Universidad', 'categoria' => 'formaciones', 'urlSello' => 'https://upvt.edomex.gob.mx/'],
            ['nombre' => 'Analista de proyectos BI', 'texto' => 'Capacítate para el empleo', 'imagen' => '2.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/93fe5238-5517-4240-99bd-28e9ac63c419'],
            ['nombre' => 'Administrador de Bases de datos', 'texto' => 'Capacítate para el empleo', 'imagen' => '3.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/7310f2a5-c860-4757-8955-97cf465175b1'],
            ['nombre' => 'Curador de datos', 'texto' => 'Capacítate para el empleo', 'imagen' => '5.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/ca94493d-12b5-4379-9e34-12fa23b0ecf7'],
            ['nombre' => 'Desarrollador BackEnd', 'texto' => 'Capacítate para el empleo', 'imagen' => '6.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/1451f39f-7016-4149-a6de-6a5f7959db20'],
            ['nombre' => 'Relaciones profesionales', 'texto' => 'Capacítate para el empleo', 'imagen' => '7.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/0b23a22e-4a54-4e74-bdb1-3ed4d743ee94'],
            ['nombre' => 'Técnico en seguridad informática (analisis de riesgos)', 'texto' => 'Capacítate para el empleo', 'imagen' => '9.svg', 'button' => 'Sello digital', 'categoria' => 'redes', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/7512a496-a67f-4f0c-9f32-b972e44e7377'],
            ['nombre' => 'Técnico en redes IP', 'texto' => 'Capacítate para el empleo', 'imagen' => '10.svg', 'button' => 'Sello digital', 'categoria' => 'redes', 'urlSello' => 'https://capacitateparaelempleo.org/verifica/2654e794-073c-484c-bcb6-ad3cc169a17d/3dfd692b-ccaf-4355-b448-adbc3e7cc327'],
            ['nombre' => 'Oracle Next Education', 'texto' => 'Formación pata programador junior', 'imagen' => '11.svg', 'button' => 'Sello digital', 'categoria' => 'formaciones', 'urlSello' => 'https://app.aluracursos.com/program/certificate/2fab0345-7d72-4ac3-8669-ecafaf746990'],
            ['nombre' => 'SQL con MySQL', 'texto' => 'Oracle Next Education', 'imagen' => '12.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/sql-mysql-proyecto-final/certificate'],
            ['nombre' => 'Spring Boot 3: Desarrollando una API REST en Java', 'texto' => 'Oracle Next Education', 'imagen' => '13.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/spring-boot-3-desarrollar-api-rest-java/certificate'],
            ['nombre' => 'Spring Boot 3: Aplique las mejores prácticas y proteja una API REST', 'texto' => 'Oracle Next Education', 'imagen' => '14.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/spring-boot-3-aplique-practicas-proteja-api-rest/certificate'],
            ['nombre' => 'Python para Data Science: Introducción al lenguaje', 'texto' => 'Oracle Next Education', 'imagen' => '15.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/python-data-science-introduccion/certificate'],
            ['nombre' => 'Python para Data Science: Funciones, librerias y pandas básico', 'texto' => 'Oracle Next Education', 'imagen' => '16.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/python-data-science-funciones-librerias-pandas-basico/certificate'],
            ['nombre' => 'Python Pandas: Tratamiento y análisis de datos', 'texto' => 'Oracle Next Education', 'imagen' => '17.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/python-pandas-tratamiento-analisis-datos/certificate'],
            ['nombre' => 'Productividad: Estrategias para actividades diarias', 'texto' => 'Oracle Next Education', 'imagen' => '18.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/productividad-parte-1-estrategias-actividades-diarias/certificate'],
            ['nombre' => 'Procedures SQL: Ejecutando codigo en MySQL', 'texto' => 'Oracle Next Education', 'imagen' => '19.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/procedures-sql-codigo-mysql/certificate'],
            ['nombre' => 'Pitch para entrevistas: Haga presentaciones impactantes', 'texto' => 'Oracle Next Education', 'imagen' => '20.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/pitch-entrevistas-presentaciones-impactantes/certificate'],
            ['nombre' => 'Persistencia con JPA: Hibernate', 'texto' => 'Oracle Next Education', 'imagen' => '21.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/persistencia-jpa-hibernate/certificate'],
            ['nombre' => 'Organización de equipos ágiles: Las funciones existentes en un equipo', 'texto' => 'Oracle Next Education', 'imagen' => '22.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/organizacion-equipos-agiles-funciones-existentes-equipo/certificate'],
            ['nombre' => 'Oracle Cloud Infrastructure: Implementación de una aplicación en la nube', 'texto' => 'Oracle Next Education', 'imagen' => '23.svg', 'button' => 'Sello digital', 'categoria' => 'cloud', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/oracle-cloud-infrastructure-implementacion-aplicacion-nube/certificate'],
            ['nombre' => 'Oracle Cloud Infrastructure: Base de datos e infraestructura', 'texto' => 'Oracle Next Education', 'imagen' => '24.svg', 'button' => 'Sello digital', 'categoria' => 'cloud', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/oracle-cloud-infrastructure-base-datos-infraestructura-codigo/certificate'],
            ['nombre' => 'Oracle Analytics: Visualizando de datos', 'texto' => 'Oracle Next Education', 'imagen' => '25.svg', 'button' => 'Sello digital', 'categoria' => 'cloud', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/oracle-analytics-visualizando-datos/certificate'],
            ['nombre' => 'Oracle Ads: Análisis de datos en la nube', 'texto' => 'Oracle Next Education', 'imagen' => '26.svg', 'button' => 'Sello digital', 'categoria' => 'cloud', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/oracle-ads-analisis-datos-nube/certificate'],
            ['nombre' => 'Machine Learning: Optmimización de modelos a través de hiperparámetros', 'texto' => 'Oracle Next Education', 'imagen' => '27.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/machine-learning-optimizacion-modelos-hiperparametros/certificate'],
            ['nombre' => 'Machine Learning: Clasificación con Sklearn', 'texto' => 'Oracle Next Education', 'imagen' => '28.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/machine-learning-clasificacion-sklearn/certificate'],
            ['nombre' => 'Machine Learning con Oracle Ads: Productividad en la creación de modelos', 'texto' => 'Oracle Next Education', 'imagen' => '29.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/oracle-ads-productividad-creacion-modelos/certificate'],
            ['nombre' => 'Lógica de programación: Primeros pasos', 'texto' => 'Oracle Next Education', 'imagen' => '30.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/logica-de-programacion-primeros-pasos/certificate'],
            ['nombre' => 'Lógica de programación: Practicando con juegos y animaciones', 'texto' => 'Oracle Next Education', 'imagen' => '31.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/logica-de-programacion-juegos-animaciones/certificate'],
            ['nombre' => 'Lógica de programación: Conceptos primordiales', 'texto' => 'Oracle Next Education', 'imagen' => '32.svg', 'button' => 'Sello digital', 'categoria' => 'otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/logica-de-programacion-conceptos-primordiales/certificate'],
            ['nombre' => 'Linkedin: Como hacer que tu perfil trabaje por ti', 'texto' => 'Oracle Next Education', 'imagen' => '33.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/linkedin-hacer-perfil-trabaje-por-ti/certificate'],
            ['nombre' => 'Lean Startup: Método eficaz para convertir una idea de negocio en empresa', 'texto' => 'Oracle Next Education', 'imagen' => '34.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/lean-startup-metodo-eficaz-idea-negocio-empresa/certificate'],
            ['nombre' => 'La empresa ágil: Introduciendo el business agility en las organizaciones', 'texto' => 'Oracle Next Education', 'imagen' => '35.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/empresa-agil-introduciendo-business-agility-organizaciones/certificate'],
            ['nombre' => 'Java: Dominando las Collections', 'texto' => 'Oracle Next Education', 'imagen' => '36.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-dominando-collections/certificate'],
            ['nombre' => 'Java y JPA: Consultas avanzadas, rendimiento y modelos complejos', 'texto' => 'Oracle Next Education', 'imagen' => '37.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-jpa-consultas-avanzadas-rendimiento-modelos-complejos/certificate'],
            ['nombre' => 'Java y JDBC: Trabajando con una Base de datos', 'texto' => 'Oracle Next Education', 'imagen' => '38.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-jdbc-trabajando-base-datos/certificate'],
            ['nombre' => 'Java Servlet: Fundamentos de programacion web con Java', 'texto' => 'Oracle Next Education', 'imagen' => '39.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-servlet-fundamentos-programacion-web-java/certificate'],
            ['nombre' => 'Java Servlet: Autenticación, autorización y MVC', 'texto' => 'Oracle Next Education', 'imagen' => '40.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-servlet-autenticacion-autorizacion-mvc/certificate'],
            ['nombre' => 'Java polimorfismo: Entendiendo herencia e interfaces', 'texto' => 'Oracle Next Education', 'imagen' => '41.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-parte-3-entendiendo-herencia-interfaces/certificate'],
            ['nombre' => 'Java OO: Entendiendo la orientacion a objetos', 'texto' => 'Oracle Next Education', 'imagen' => '42.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-parte2-introduccion-orientada-objetos/certificate'],
            ['nombre' => 'Java JRE y JDK: Compile y ejecute si primer programa', 'texto' => 'Oracle Next Education', 'imagen' => '43.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-primeros-pasos/certificate'],
            ['nombre' => 'Java excepciones: Aprenda a crear, lanzar y controlar excepciones', 'texto' => 'Oracle Next Education', 'imagen' => '44.svg', 'button' => 'Sello digital', 'categoria' => 'backend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/java-excepciones/certificate'],
            ['nombre' => 'Introducción a SQL con MySQL: Manipule y consulte datos', 'texto' => 'Oracle Next Education', 'imagen' => '45.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/introduccion-sql-mysql-manipule-consulte-datos/certificate'],
            ['nombre' => 'HTML5 y CSS3: Avanzando en CSS', 'texto' => 'Oracle Next Education', 'imagen' => '46.svg', 'button' => 'Sello digital', 'categoria' => 'frontend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/html5-css3-avanzando-css/certificate'],
            ['nombre' => 'HTML5 y CSS3: Trabajando con formularios y tablas', 'texto' => 'Oracle Next Education', 'imagen' => '47.svg', 'button' => 'Sello digital', 'categoria' => 'frontend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/html5-css3-formularios-tablas/certificate'],
            ['nombre' => 'HTML5 y CSS3: Posicionamiento, listas y navegación', 'texto' => 'Oracle Next Education', 'imagen' => '48.svg', 'button' => 'Sello digital', 'categoria' => 'fronted', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/html5-css3-posicionamiento-listas-navegacion/certificate'],
            ['nombre' => 'HTML5 y CSS3: Mi primera página web', 'texto' => 'Oracle Next Education', 'imagen' => '49.svg', 'button' => 'Sello digital', 'categoria' => 'frontend', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/html5-css3-primera-pagina-web/certificate'],
            ['nombre' => 'Hábitos: Ser productivo para cumplir sus metas profesionales', 'texto' => 'Oracle Next Education', 'imagen' => '50.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/habitos-productivo-metas-personales/certificate'],
            ['nombre' => 'Git y GitHub: Controle y comparta su código', 'texto' => 'Oracle Next Education', 'imagen' => '51.svg', 'button' => 'Sello digital', 'categoria' => 'herramientas', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/git-github-control-version/certificate'],
            ['nombre' => 'Gestión ágil: Lidernando el cambio en un ambiente de agilidad: Controle y comparta su código', 'texto' => 'Oracle Next Education', 'imagen' => '52.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/gestion-agil-liderando-cambio/certificate'],
            ['nombre' => 'Fundamentos de agilidad: Primeros pasos para la transformación ágil', 'texto' => 'Oracle Next Education', 'imagen' => '53.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/fundamentos-agilidad-primeros-pasos-transformacion-agil/certificate'],
            ['nombre' => 'Foco: Enfocarse trae más resultados para el día a día', 'texto' => 'Oracle Next Education', 'imagen' => '54.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/foco-habito-dia-a-dia/certificate'],
            ['nombre' => 'Emprendimiento: De la idea al plan de negocios', 'texto' => 'Oracle Next Education', 'imagen' => '55.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/emprendimiento-idea-plan-negocios/certificate'],
            ['nombre' => 'Data Visualization: Explorando con Seaborn', 'texto' => 'Oracle Next Education', 'imagen' => '56.svg', 'button' => 'Sello digital', 'categoria' => 'Otros', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/data-visualization-seaborn/certificate'],
            ['nombre' => 'Consultas SQL: Avanzando en SQL con MySQL', 'texto' => 'Oracle Next Education', 'imagen' => '57.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/consultas-sql-mysql/certificate'],
            ['nombre' => 'Comandos DML: Manipulación de datos con MySQL', 'texto' => 'Oracle Next Education', 'imagen' => '58.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/comandos-dml-manipulacion-datos-mysql/certificate'],
            ['nombre' => 'Business model canvas: Avanzando con tu modelo de negocios', 'texto' => 'Oracle Next Education', 'imagen' => '59.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/business-model-canvas-parte-2-modelo-negocios/certificate'],
            ['nombre' => 'Business model canvas: Un modelo poderoso para tu negocio', 'texto' => 'Oracle Next Education', 'imagen' => '60.svg', 'button' => 'Sello digital', 'categoria' => 'softSkills', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/business-model-canvas-parte-1-modelo-poderoso-negocio/certificate'],
            ['nombre' => 'Administración de MySQL: Seguridad y optimización de la base de datos ', 'texto' => 'Oracle Next Education', 'imagen' => '62.svg', 'button' => 'Sello digital', 'categoria' => 'dataBase', 'urlSello' => 'https://app.aluracursos.com/user/juarez-sanchez-luisjair/course/mysql-seguridad-optmizacion-base-datos-parte1/certificate'],
            ['nombre' => 'Formacion SQL con MySQL ', 'texto' => 'Formacion de todos los aspectos de SQL con MySQL', 'imagen' => '67.svg', 'button' => 'Sello digital', 'categoria' => 'formaciones', 'urlSello' => 'https://app.aluracursos.com/degree/certificate/d6e813ca-0cef-4f24-8273-cc58677641c3'],
        ];

        return view('inicio', compact('cardAcademic'));
    }
}
